# Generated by Django 4.1.7 on 2023-03-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
    ]
