# Generated by Django 4.1.7 on 2023-03-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='karta',
        ),
    ]
