# Generated by Django 4.1.7 on 2023-03-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_location_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
