# Generated by Django 4.1.7 on 2023-03-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
